AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Project2DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ethomas-p2-db
      AttributeDefinitions:
      - AttributeName: movieId
        AttributeType: S
      - AttributeName: title
        AttributeType: S
      KeySchema:
      - AttributeName: movieId
        KeyType: HASH
      - AttributeName: title
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Environment

Outputs:
  Project2DynamoDBTable:
    Value: !GetAtt Project2DynamoDBTable.Arn
    Export:
      Name: Project2DynamoDBTable